# Generated by Django 3.2 on 2022-03-10 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('golf_booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='user',
            new_name='booking_id',
        ),
    ]
