# Generated by Django 3.2 on 2022-03-11 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf_booking', '0002_rename_user_booking_booking_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Confirmed')], default=0),
        ),
    ]
