# Generated by Django 3.2 on 2022-03-11 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf_booking', '0004_alter_booking_booking_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='play_date',
            field=models.DateField(null=True),
        ),
    ]
