# Generated by Django 3.2 on 2022-03-16 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf_booking', '0006_alter_booking_play_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='extra_requests',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='play_time',
            field=models.CharField(choices=[('08:00', '08:00'), ('09:00', '09:00'), ('10:00', '10:00'), ('11:00', '11:00'), ('12:00', '12:00'), ('13:00', '13:00'), ('14:00', '14:00'), ('15:00', '15:00'), ('16:00', '16:00'), ('17:00', '17:00')], default=False, max_length=10),
        ),
    ]
