# Generated by Django 3.2 on 2022-03-16 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf_booking', '0007_auto_20220316_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='play_time',
            field=models.CharField(choices=[('08:00', '08:00'), ('08:30', '08:30'), ('09:00', '09:00'), ('09:30', '09:30'), ('10:00', '10:00'), ('10:30', '10:30'), ('11:00', '11:00'), ('11:30', '11:30'), ('12:00', '12:00'), ('12:30', '12:30'), ('13:00', '13:00'), ('13:30', '13:30'), ('14:00', '14:00'), ('14:30', '14:30'), ('15:00', '15:00'), ('15:30', '15:30'), ('16:00', '16:00'), ('16:30', '16:30'), ('17:00', '17:00')], default=False, max_length=10),
        ),
    ]
