# Generated by Django 3.2 on 2022-03-16 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_auto_20220310_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('I Prefer Not To Say', 'I Prefer Not To Say'), ('Male', 'Male'), ('Female', 'Female')], default=False, max_length=20),
        ),
    ]
